### PR TITLE
fix: defensive programming for cabalDetails.getUsers() function

### LINKED ISSUE #268: Stuck on loading screen in v6.0.2
Both in the appImage and built from source, it stays stuck on a loading screen when i start it ("loading hypercores" or whatever). v6.0.1 works fine. My node version is v13.2.0, but I assume that's not super relevant given that I see the issue in the appimage and not just when building from source.

### PR DESCRIPTION
**Pull request by okdistribute**
Hey all,

This fixes #268 #264 , maybe other recent GitHub issues. This happened due to malformed data on the network sent from someone's cabal instance.

Practically, (beyond the scope of this particular defensive PR), getUser ought to  be a function implemented internally inside cabalDetails. cabalDetails ought to also use this getUser function internally instead of `()[]` which is extremely fragile, and supply a default user if that user is malformed. I didn't have time to also do a PR there, though. 

Overall, a single peer sending malformed data should not mess up everyone else's clients. Some more defensiveness lower in the stack (cabal-core/client) will become even more crucial as more people decide to write their own clients (!good thing!) and also make it easier to write new clients in other languages as well as bridges to other networks (e.g., matrix, irc) if you know what fields each message type should have (Woo lets have more impl.!)

### CODE REVIEW

**Comment by todrobbins** [comment]
thank you @okdistribute!

File: app/containers/channelPanel.js [hunk 1]
```diff
@@ -37,8 +34,6 @@ const mapDispatchToProps = dispatch => ({
 })
 
 function ChannelPanel (props) {
-  const user = props.getUsers({ addr: props.addr })[props.userKey]
```
Comment (okdistribute) [inline app/containers/channelPanel.js:40]: woo removed unnecessary getUsers call!

File: app/actions.js [hunk 2]
```diff
@@ -291,22 +289,30 @@ export const onIncomingMessage = ({ addr, channel, message }, callback) => (disp
 
   const settings = getState().cabalSettings[addr]
   if (!!settings.enableNotifications && !document.hasFocus()) {
-    const users = cabalDetails.getUsers()
```
Comment (okdistribute) [inline app/actions.js:294]: woo removed unecessary getUsers call for EACH incoming message :O

File: app/containers/messages.js [hunk 3]
```diff
@@ -50,8 +50,8 @@ function MessagesContainer (props) {
     return (
       <div className='messages'>
         {messages.map((message) => {
-          const user = props.getUsers({ addr: props.addr })[message.key]
```
Comment (okdistribute) [inline app/containers/messages.js:53]: Woo removed unecessary getUsers call for EACH RENDERED MESSAGE!!!

**Comment by nikolaiwarner** [comment]
works great! thanks @okdistribute!! 💎💎💎💎
